aurafinance/aura-contracts

- README.md
- contracts/ClaimFeesHelper.sol
- contracts/mocks/balancer/MockFeeDistro.sol
- tasks/deploy/index.ts
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet-post-phases.ts
- test-fork/ClaimFeesHelper.spec.ts
refactors claim fees helper to add checkpoint
> refactor: refactors claim fees helper to add checkpoint

- README.md
- contracts/BoosterHelper.sol
- contracts/ClaimFeesHelper.sol
- tasks/deploy/mainnet-post-phases.ts
- tasks/snapshot/index.ts
- test-fork/ClaimFeesHelper.spec.ts
- test-fork/FeeDistroUpdate.spec.ts
Removes             uint256 claimed = feeDistro.claimToken(voterProxy, _token);
> refactor: removes feeDistro.claimToken call from helper

- README.md
- package.json
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet-post-phases.ts
- tasks/utils/signerFactory.ts
- test-fork/ClaimFeesHelper.spec.ts
- yarn.lock
- updates boosterHelper address 
- updates claimsFeesHelper address 
- adds the capacity to get a signer from defender on hh tasks
> chore: updates boosterHelper and feesCollector address on readme

- README.md
chore: adds test coverage badge
> chore: adds test coverage badge

- tasks/snapshot/gauge_snapshot.json
- tasks/snapshot/index.ts
|Gauge                       |address                                   |
|--------------------|------------------------------|
|BPT-rETH-ETH|0xfb0265841C49A6b19D70055E596b212B0dA3f606 |
|FOLD:WETH|0xAf3c3dab54ca15068D09C67D128344916e177cA9 |
|Gauge                       |address                                   |
|--------------------|------------------------------|
|80/20 UNN/WETH              |0x8F4a5C19A74D7111bC0e1486640F0aAB537dE5A1|
|50/50 WETH/USDT             |0xdB7D7C535B4081Bb8B719237bdb7DB9f23Cc0b83|
|50/50 UMA/USDC              |0xf4339872Ad09B34a29Be76EE81D4F30BCf7dbf9F|
|a-20/80 WETH/GNO            |0x981Fb05B738e981aC532a99e77170ECb4Bc27AEF|
|a-80/20 MAGIC/WETH          |0x785F08fB77ec934c01736E30546f87B4daccBe50|
|a-Stable DAI/USDT/USDC …
> feat: update gauges

- tasks/snapshot/proposals.json
Adds latest aug 17 vote to the proposal list.
> [FEAT] update proposal list

- contracts/ClaimFeesHelper.sol
- contracts/CrvDepositorWrapper.sol
- contracts/CrvDepositorWrapperWithFee.sol
- contracts/Interfaces.sol
- test-fork/CrvDepositorWrapperProxy.spec.ts
- test-fork/CrvDepositorWrapperWithFee.spec.ts
**CrvDepositorWrapperWithFee**
As per [AIP-13](https://vote.aura.finance/#/proposal/0xd7a1663c27e7390898fda71244065b13be5047768020e0df6ba255b67c0ae3bf), the overall system fees are to be increased to 25%, with auraBAL going to 20.5. It is not possible to set any individual fee past 15%, so must create an intermediary for the CvxStakingProxy.
- Creates new CrvDepositorWrapperWithFee, taking a % of incoming and moving it to auraBAL
- Adds fork test for upgrade pipeline
> feat: AIP-13 resolution

- tasks/snapshot/index.ts
As per new docs: https://github.com/aurafinance/aura-docs/commit/df3fa9318e3de5eb227e010c517b5fab2d6f61e6
> [FEAT] Lower vote threshold to 0.2%

- README.md
- contracts/GaugeMigrator.sol
- tasks/deploy/mainnet-post-phases.ts
- test-fork/AddSameLpTokenTwice.spec.ts
- renames migrator
- adds fork test scenarios
> refactor: renames LPMigrator to GaugeMigrator

- tasks/snapshot/gauge_snapshot.json
- tasks/snapshot/proposals.json
New gauges added:
[0x74CE2247eC3f0b87BA0737497e3Db8873c184267](https://etherscan.io/address/0x74CE2247eC3f0b87BA0737497e3Db8873c184267)
[0xa26B3523227e300Ff8eCA69CD3b0bdcbd2Db0313](https://etherscan.io/address/0xa26B3523227e300Ff8eCA69CD3b0bdcbd2Db0313)
[0x8F5F5b412dA3cB958c4d26444D9FA7ED11fD3F27](https://etherscan.io/address/0x8F5F5b412dA3cB958c4d26444D9FA7ED11fD3F27)
[0x9C0f4144D037688e0AdA74B22a9aAb7c14c58e6C](https://etherscan.io/address/0x9C0f4144D037688e0AdA74B22a9aAb7c14c58e6C)
[0x610f1569045041Af6212be048Bc43e8DC6a07b55](https://etherscan.io/address/0x610f1569045041Af6212be048Bc43e8DC6a07b55)
> [FEAT]: Vote 13th Oct

- .github/workflows/test-fork.yaml
- .solcover.js
- contracts/_mocks/cross-chain/DummyBridge.sol
- contracts/_mocks/cross-chain/DummySiphonGauge.sol
- contracts/_mocks/cross-chain/LZEndpointMock.sol
- contracts/cross-chain/L2Coordinator.sol
- contracts/cross-chain/SiphonDepositor.sol
- contracts/cross-chain/SiphonGauge.sol
- contracts/cross-chain/layer-zero/interfaces/ILayerZeroEndpoint.sol
- contracts/cross-chain/layer-zero/interfaces/ILayerZeroReceiver.sol
- contracts/cross-chain/layer-zero/interfaces/ILayerZeroUserApplicationConfig.sol
- contracts/cross-chain/layer-zero/lzApp/LzApp.sol
- contracts/cross-chain/layer-zero/lzApp/NonblockingLzApp.sol
- contracts/cross-chain/layer-zero/token/oft/IOFTCore.sol
- contracts/cross-chain/layer-zero/util/ExcessivelySafeCall.sol
- scripts/deployCrossChain.ts
- tasks/snapshot/index.ts
- test-fork/CrossChainDeposits.spec.ts
- test/cross-chain/L2Coordinator.spec.ts
- test/cross-chain/SiphonDepositor.spec.ts
- test/cross-chain/SiphonGauge.spec.ts
- Siphon Depositor : removes unused events 
- Removes eslint errors
- Adds test coverage for SiphonDepositor
- Adds test coverage for SiphonGauge
- Adds test coverage for L2Coordinator
- Updates solidity coverage npm depencies
> test: adds cross-chain unit tests

- tasks/snapshot/gauge_snapshot.json
- tasks/snapshot/index.ts
- tasks/snapshot/proposals.json
138: 0xF60B8DAF6825c9fBE5eC073D623B9d47cDa592E8
139: 0x651361a042e0573295dd7f6A84dBD1DA56DAc9D5
140: 0xb8F91FF8Cd5005f6274B6c2292CF3CCCdBCF32b7
141: 0x97a92eDcDD4176B1495bF5DA6D9547537A53ED72
142: 0x8B815a11D0D9eeeE6861D1C5510d6FAA2C6e3fEb
143: 0xeC6BA3d9D9045997552155599E6Cc89aA08Ffd76
144: 0x79C14b9655e1C4AB42836768b8938357cD8Fc5d3
145: 0xb32Ae42524d38be7E7eD9E02b5F9330fCEf07f3F
> feat: gauges update

- tasks/snapshot/gauge_snapshot.json
- tasks/snapshot/index.ts
- tasks/snapshot/proposals.json
- 0x285cBA395e3Acb82A42758638fA85da9936016a4
- 0x7Fc115BF013844D6eF988837F7ae6398af153532
> feat: added new gauges

- tasks/snapshot/gauge_snapshot.json
- tasks/snapshot/index.ts
- tasks/snapshot/proposals.json
- 171: `0x519cCe718FCD11AC09194CFf4517F12D263BE067`
- 170: `0x01A9502C11f411b494c62746D37e89d6f7078657`
- 169: `0x3d5F0520267FE92FFf52B847FAC3204554552f99`
- 168: `0xD9Ea099D62526e670aef2BD680599FC48c409f3c`
- 167: `0x21a3De9292569F599e4cf83c741862705bf4f108`
- 166: `0xBC02eF87f4E15EF78A571f3B2aDcC726Fee70d8b`
- 165: `0x81C452E84B103555C2Dd2DEc0bFABC0c4d6B3065`
> [Feat] Gauge vote 19th Jan 2023

- contracts/_mocks/compounder/MockStrategy.sol
- contracts/compounder/GenericVault.sol
- contracts/compounder/Strategy.sol
- contracts/compounder/StrategyBase.sol
- contracts/compounder/rewardHandlers/BBUSDHandler.sol
- contracts/compounder/rewardHandlers/BalancerSwapsHandler.sol
- contracts/compounder/rewardHandlers/HandlerBase.sol
- contracts/interfaces/IERC4626.sol
- scripts/deployVault.ts
- test-fork/AuraBalVault.spec.ts
- test-utils/assertions.ts
- test/compounder/AuraBalVault.spec.ts
- test/compounder/GenericUnionVault.spec.ts
- test/shared/ERC20.behaviour.ts
- test/shared/ERC4626.behaviour.ts
adds unit test coverage to generic union vault
> test(compounder): add unit test for generic union vault

- test-fork/AddSameGaugeTwice.spec.ts
Shuts down and adds the same gauge
> test: add duplicate gauge

- scripts/deployVault.ts
fix(deployment vault script): fix allowance on deployment vault script
> fix(deployment vault script): fix allowance on deployment vault script

- .gitignore
- contracts/peripheral/AuraClaimZapV2.sol
- scripts/deployAuraClaimZapV2.ts
- tasks/deploy/goerli.ts
- tasks/deploy/mainnet-post-phases.ts
- test-fork/AuraClaimZapV2.spec.ts
* removed enum and option bit shifting & introduced options struct
* add an option to deposit to compounder
* reduce calls to cvxcrv rewards/compounder
* gas optimisation on user balance reads
* helper functions to reduce code repetition
* clarity around option names
> feat: claimzap v2

- package.json
- tasks/information/booster-info.ts
- yarn.lock
Added killed and period end columns
> [Feat] added reward status

- tasks/information/booster-info.ts
Changes API url to get the proper tvl values and decouples pid 2 from pid 58 as it was wrongly mark as match
> fix(tasks): fixes tvl calculations on info:booster:pools-tvl task

- contracts/compounder/AuraBalVault.sol
- contracts/compounder/FeeForwarder.sol
- contracts/compounder/GenericVault.sol
- contracts/compounder/Strategy.sol
- contracts/interfaces/IBasicRewards.sol
- contracts/interfaces/IVirtualRewards.sol
- scripts/deployVault.ts
- test-fork/AuraBalVault.spec.ts
- test/compounder/AuraBalVault.spec.ts
- test/compounder/FeeForwarder.spec.ts
- test/compounder/GenericUnionVault.spec.ts
- test/rewards/VirtualBalanceRewardPool.spec.ts
- test/shared/ERC4626.behaviour.ts
- yarn.lock
- Pass `shares` instead of assets `amount` to `extraReward.stake` during deposit
> [Feat] boosted auraBAL compounder (review)

- .solcover.js
- contracts/_mocks/compounder/MockStrategy.sol
- contracts/compounder/GenericVault.sol
- contracts/compounder/StrategyBase.sol
- contracts/interfaces/balancer/IBalancerCore.sol
- test-fork/AuraBalVault.spec.ts
- test-utils/assertions.ts
- test/compounder/AuraBalVault.spec.ts
- test/compounder/GenericUnionVault.spec.ts
- test/shared/ERC4626.behaviour.ts
- adds test to min out harvest calculations
> test(compounder): adds test to min out harvest calculations

- README.md
- contracts/peripheral/AuraClaimZapV3.sol
- scripts/deployAuraClaimZapV3.ts
- tasks/deploy/goerli.ts
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet-post-phases.ts
- test-fork/peripheral/AuraClaimZapV3.spec.ts
- test/peripheral/AuraClaimZapV3.spec.ts
v2:
removed enum and option bit shifting & introduced options struct
add an option to deposit to compounder
reduce calls to cvxcrv rewards/compounder
gas optimisation on user balance reads
helper functions to reduce code repetition
clarity around option names
> [Feat] aurabal compounder claimzap

- contracts/_mocks/balancer/MockBalancerPoolToken.sol
- contracts/_mocks/balancer/MockBalancerVault.sol
- contracts/_mocks/balancer/MockFeeDistro.sol
- contracts/_mocks/curve/MockCurveVoteEscrow.sol
- contracts/peripheral/grants/VeBalGrant.sol
- scripts/deployMocks.ts
- scripts/deployVeBalGrant.ts
- test-fork/peripheral/grants/VeBalGrant.spec.ts
- test/peripheral/grants/VeBalGrant.spec.ts
-  adds unit test to veBalGrant
> test(vebalgrant): adds unit test to veBalGrant

- .github/workflows/test-coverage.yaml
ci(coverage): disables test coverage on [WIP] prs
> ci(coverage): disables test coverage on [WIP] prs

- README.md
- contracts/sidechain/Coordinator.sol
- contracts/sidechain/Create2Factory.sol
- hardhat.config.ts
- package.json
- scripts/deploySidechain.ts
- scripts/deploySystem.ts
- tasks/deploy/index.ts
- tasks/deploy/sidechain-config.ts
- tasks/deploy/sidechain.ts
- tasks/utils/deploy-utils.ts
- tasks/utils/etherscan.ts
- tasks/utils/networkAddressFactory.ts
- test-fork/sidechain/Sidechain.spec.ts
- yarn.lock
adds arbitrum configurations and create2Factory
> feat(arbitrum): adds arbitrum configurations

- tasks/information/incentives.ts
style(incentives): improves info:hh:incentives task logs
> style(incentives): improves info:hh:incentives task logs

- contracts/sidechain/AuraBalOFT.sol
- contracts/sidechain/AuraBalProxyOFT.sol
- contracts/sidechain/AuraOFT.sol
- contracts/sidechain/AuraProxyOFT.sol
- contracts/sidechain/Create2Factory.sol
- contracts/sidechain/CrossChainConfig.sol
- contracts/sidechain/CrossChainMessages.sol
- contracts/sidechain/L1Coordinator.sol
- contracts/sidechain/L2Coordinator.sol
- contracts/sidechain/bridge/BridgeDelegateReceiver.sol
- contracts/sidechain/bridge/BridgeDelegateSender.sol
- contracts/sidechain/bridge/SimpleBridgeDelegateSender.sol
- contracts/sidechain/interfaces/IL1Coordinator.sol
- Adds missing nat spec 
- refactor approve for safeApprove
- refactor transfer for safeTransfer
> fix(sidechain): changes approve, transfer for safeApprove and safeTransfer

- contracts/sidechain/AuraBalProxyOFT.sol
- contracts/sidechain/AuraOFT.sol
- contracts/sidechain/AuraProxyOFT.sol
- contracts/sidechain/CrossChainConfig.sol
- contracts/sidechain/L1Coordinator.sol
- contracts/sidechain/L2Coordinator.sol
- contracts/sidechain/PausableProxyOFT.sol
- contracts/sidechain/bridge/BridgeDelegateSender.sol
- Adds missing events
- Fixes slither issues
> fix(sidechain): fixes slither issues

- README.md
- Adds address of auraViewHelpers
> chore: updates readme with auraViewHelpers address

- tasks/information/booster-info.ts
upgrade url to retrieve tvl from pools on booster info task
> fix(info): upgrade url to retrieve tvl from pools on boster info task

- tasks/information/hiddenhandApi.ts
- tasks/information/incentives.ts
- tasks/information/paladinApi.ts
Add new hardhat task to create paladin quests to incentivise veBal markets
> feat(tasks): adds create:paladin:incentives task

- README.md
- tasks/information/incentives.ts
fixes approval address on hardhat task to create paladin quests
> fix(tasks): fix approval error on paladin quest creation

- README.md
- contracts/sidechain/README.md
- tasks/deploy/arbitrum-config.ts
- tasks/deploy/mainnet-config.ts
Updates keeper multicall address
> docs(docs): updates deployed addresses

- package.json
- tasks/information/aura-supply-circulation.ts
- tasks/information/index.ts
- yarn.lock
Add task to compare total supply vs total circulation
> feat: adds  task info:aura:supply-circulation

- README.md
- tasks/deploy/base-config.ts
- tasks/information/aura-supply-circulation.ts
- tasks/information/hiddenhandApi.ts
- tasks/information/incentives.ts
- tasks/protocol/index.ts
- tasks/utils/balancerApi.ts
- Updates calculations to generate tx builder file in order to match hidden hand v2 new params
> feat: update incentives task to match with hh v2

- tasks/deploy/base-config.ts
- tasks/protocol/index.ts
- tasks/utils/auraApi.ts
- Updates address at tasks/deploy/base-config.ts
- Adds support for base network on gauge vote rewards scripts
> feat: gauge vote rewards adds support for base

- contracts/peripheral/BoosterHelper.sol
- contracts/rewards/ChildGaugeVoteRewards.sol
- scripts/deployPeripheral.ts
- tasks/deploy/sidechain.ts
- test-fork/peripheral/BoosterHelper.spec.ts
- Add extra capabilities to booster helper
> feat: booster helper v2

- .solcover.js
- contracts/peripheral/BoosterHelper.sol
- contracts/peripheral/PayableMulticall.sol
- contracts/sidechain/README.md
- deployments/1.json
- scripts/deployPeripheral.ts
- scripts/deployVault.ts
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet-post-phases.ts
- tasks/deploy/sidechain-constants.ts
- tasks/deploy/sidechain.ts
- tasks/information/aura-supply-circulation.ts
- tasks/protocol/index.ts
- test-fork/compounder/FeesTokenHandlersV4.spec.ts
- test-fork/peripheral/BoosterHelper.spec.ts
- test-fork/sidechain/peripheral/PayableMulticallSidechain.spec.ts
> feat: add PayableMulticall

- tasks/protocol/index.ts
- tasks/utils/auraApi.ts
- tasks/utils/balancerApi.ts
adds support to zkevm to add pool task
> feat: adds support to zkevm to add pool task

- tasks/deploy/avax-config.ts
- tasks/protocol/index.ts
- yarn.lock
- Updates convex submodule
- Updates avalanche minter address 
- Adds validation to hh task to avoid adding non deposit pools (ie 80-20)
> chore: updates convex submodule

- contracts/_mocks/balancer/MockOFTWithFee.sol
- contracts/layerzero/token/oft/extension/IOFTWithFee.sol
- contracts/sidechain/bridge/OftWithFeeBridgeSender.sol
- scripts/deployBridgeDelegates.ts
- tasks/deploy/sidechain.ts
- test/sidechain/OftWithFeeBridgeSender.spec.ts
- Avalanche BAL is an OFTWithFee therefore an update to the bridge sender
> feat: adds OftWithFeeBridgeSender

- contracts/compounder/rewardHandlers/BBUSDHandler.sol
- contracts/compounder/rewardHandlers/BalancerHandlerBase.sol
- contracts/compounder/rewardHandlers/BalancerSwapsHandler.sol
- contracts/compounder/rewardHandlers/UniswapRouterHandler.sol
- contracts/interfaces/IUniswapV3SwapRouter.sol
- scripts/deploySystem.ts
- scripts/deployVault.ts
- tasks/deploy/goerli-config.ts
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet-post-phases.ts
- test-fork/compounder/FeesTokenHandlersV5.spec.ts
- test/compounder/AuraBalVault.spec.ts
- test/compounder/BalancerSwapsHandler.spec.ts
- test/shared/HandlerBase.behaviour.ts
- yarn.lock
Changes feeHandler for swapping between USDC to WETH with a a deeper pool to improve efficiency
> feat: adds feeHandlerV5 UniswapRouterHandler

- .env.example
- tasks/contract-status/index.ts
- tasks/deploy/arbitrum-config.ts
- tasks/deploy/avax-config.ts
- tasks/deploy/base-config.ts
- tasks/deploy/gnosis-config.ts
- tasks/deploy/optimism-config.ts
- tasks/deploy/polygon-config.ts
- tasks/deploy/zkevm-config.ts
- tasks/index.ts
- tasks/snapshot/result.ts
- types/sidechain-types.ts
Add a hardhat task to perform some check on ecosystem contracts:
- check contract owner
- check that contract is verified on explorer
- check that contract is tagged on explorer
> Status script

- tasks/contract-status/index.ts
don't check ownership of multicall contracts
> chore: multicall owner

- .gitmodules
- .solcover.js
- contracts/_mocks/balancer/MockBalancerPoolToken.sol
- contracts/_mocks/balancer/MockBalancerVault.sol
- contracts/core/CrvDepositorWrapperForwarderV2.sol
- contracts/interfaces/balancer/IBalancerCore.sol
- contracts/utils/balancer/FixedPoint.sol
- contracts/utils/balancer/LogExpMath.sol
- contracts/utils/balancer/Math.sol
- contracts/utils/balancer/StableMath.sol
- package.json
- scripts/deploySystem.ts
- tasks/deploy/mainnet-config.ts
- tasks/deploy/mainnet.ts
- test-fork/core/CrvDepositorForwarderV2.spec.ts
- test/core/CrvDepositorForwarderV2.spec.ts
- yarn.lock
- Add news crv depositor wrapper that swaps auraBal instead of minting new one.
- Unit test 
- Fork test to proof the getMinOut is correctly calculated
> feat:  adds crv depositor wrapper forwarder v2

- contracts/peripheral/AuraViewHelpersLite.sol
- contracts/sidechain/README.md
- scripts/deploySidechain.ts
- tasks/deploy/sidechain.ts
- tasks/utils/deploy-utils.ts
- test-fork/sidechain/view/SidechainView.spec.ts
adds vlAura info  to AuraViewHelpersLite
change to create2 the deployment of helpers
> feat: adds vlAura info  to AuraViewHelpersLite

- LICENSE.md
- funding.json
- scripts/deploySystem.ts
- tasks/deploy/mainnet-post-phases.ts
- test/convex-platform/PoolFeeManagerProxy.spec.ts
- test/sidechain/sidechainTestSetup.ts
- yarn.lock
Adds Booster FeeManager fns and PoolManagerV4 fns to PoolFeeManagerProxy
> feat: adds PoolFeeManagerProxy

- tasks/deploy/mainnet-config.ts
- tasks/information/gauge-info.ts
- tasks/information/incentives.ts
- tasks/protocol/index.ts
- tasks/shutdown/index.ts
- tasks/utils/networkAddressFactory.ts
- tasks/utils/signerFactory.ts
- Add task to verify which pools ids are missing on the gauge voter rewards contract. 
- Updates incentive tasks figures
- Update shutdown script with new pool manager wrappers
> feat: add task protocol:gaugeVoter-getPoolIds

- .github/workflows/snapshot-gauge-votes.yaml
- scripts/automations/snapshot-generate.sh
- tasks/snapshot/create.ts
- tasks/snapshot/generate.ts
Allows to generate the gauge options automatically on Thursdays
> feat: automate snapshot:generate on github action

- tasks/deploy/goerli-config.ts
- tasks/deploy/mainnet-config.ts
- tasks/information/incentives.ts
- tasks/protocol/index.ts
- tasks/protocol/safe.ts
- Refactor to current protocol hardhat tasks 
- Adds taks for protocol - keeper
> refactor: protocol hardhat taks improvements

- tasks/information/hiddenhandApi.ts
- tasks/utils/balancerApi.ts
- Fix calculations of veBALPrice and maxTokensPerVote
> fix: calculation of veBALPrice

- tasks/snapshot/gauge_choices.json
Add missing gauge
{ "address": "0x9fdd52efeb601e4bc78b89c6490505b8ac637e9f", "label": "Stable waEthUSDC/waEthUSDT/Aave Prime GHO" },
> fix: adds missing gauge to gauge_choices.json

- tasks/snapshot/constants.ts
- tasks/snapshot/generate.ts
- tasks/snapshot/utils.ts
> fix: priorityGaugesAddresses killed

- scripts/reduceRewardMultipliers.ts
- tasks/information/gauge-info.ts
- tasks/protocol/index.ts
- tasks/snapshot/result.ts
- tasks/snapshot/utils.ts
- tasks/utils/auraApi.ts
- Check if the poolId is set on gauge voter
- Updates addresses on task  protocol:booster:reduceRewardMultiplier
- Improve speed on task info:gauges:killed-gauges
> fix: protocol add pool task missing setPoolId call

- tasks/deploy/mainnet.ts
- tasks/information/aura-supply-circulation.ts
- tasks/sidechain/sidechain-tasks.ts
- Review remote address enabled for ofts
> chore: improves task sidechain:aura-oft-info

- tasks/snapshot/gauge_choices.json
- tasks/snapshot/proposals.json
> feat: vote 03 July 2025
